include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gen.dart"
    - lib/generated/**
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
    deprecated_member_use: ignore

linter:
  rules:
    # Style
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_unnecessary_containers: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    unawaited_futures: true
    unnecessary_await_in_return: true
    use_build_context_synchronously: true
